Repository MetPX/sarracenia, pull requests merged in 2024-06, with the labels that each got.

#1049 adding new_pathWrite() as per Reid suggestion
  sarracenia/__init__.py
Labels: enhancement, likely-fixed

#1093 fix #1091 download and/or sender plugin error crashes
  sarracenia/flow/__init__.py
Labels: bug, crasher

#1109 fix crash where 'dictionary changed size during iteration'
  sarracenia/flowcb/retry.py
Labels: bug
